jobs:
- job: NPMPublish
  displayName: NPM Publish
  pool:
    name: cxeiss-ubuntu-20-04-large
    image: cxe-ubuntu-20-04-1es-pt
    os: linux
  variables:
    - name: BUILDSECMON_OPT_IN
      value: true

  timeoutInMinutes: 90
  cancelTimeoutInMinutes: 5
  templateContext:
    outputs:
      - output: pipelineArtifact
        targetPath: $(System.DefaultWorkingDirectory)
        artifactName: github-npm-js-publish
  steps:
    - checkout: self
      clean: true
      fetchFilter: blob:none
      persistCredentials: true

    - task: UseNode@1
      inputs:
        version: '22.22.0'
      displayName: 'Use Node.js 22.22.0'

    - template: /.ado/templates/configure-git.yml@self

    - script: |
        yarn install
      displayName: Install npm dependencies

    - script: |
        node .ado/scripts/configure-publish.mts --verbose
      displayName: Verify release config

    # Disable Nightly publishing on the main branch
    - ${{ if endsWith(variables['Build.SourceBranchName'], '-stable') }}:
      - script: |
          yarn config set npmPublishAccess public
          yarn config set npmPublishRegistry "https://registry.npmjs.org"
          yarn config set npmAuthToken $(npmAuthToken)
        displayName: Configure yarn for npm publishing
        condition: and(succeeded(), eq(variables['publish_react_native_macos'], '1'))

      - script: |
          yarn workspaces foreach -vv --all --topological --no-private npm publish --tag $(publishTag) --tolerate-republish
        displayName: Publish packages
        condition: and(succeeded(), eq(variables['publish_react_native_macos'], '1'))

      - script: |
          node .ado/scripts/apply-additional-tags.mjs --tags "$(additionalTags)"
        displayName: Apply additional dist-tags
        condition: and(succeeded(), eq(variables['publish_react_native_macos'], '1'))
        env:
          NODE_AUTH_TOKEN: $(npmAuthToken)

    - script: |
        yarn config unset npmPublishAccess || true
        yarn config unset npmAuthToken || true
        yarn config unset npmPublishRegistry || true
      displayName: Remove NPM auth configuration
      condition: always()
